spring:
  application:
      name: translator
  profiles:
    active: dev

logging:
  level:
    root: info

application:
  properties:
    logging:
      logRequest: true
      logResponse: true
      logRequestForUrls: /*

---
spring:
  profiles: dev

server:
  port: 8977

---
spring:
  profiles: aws-staging

server:
  port: 8977


