spring:
  application:
      name: translator

logging:
  level:
    root: info
---
spring:
  profiles: local

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

server:
  port: 8977


