spring:
  application:
      name: translator
  profiles:
    active: aws

logging:
  level:
    root: info

application:
  properties:
    logging:
      logRequest: true
      logResponse: true
      logRequestForUrls: /*

---
spring:
  profiles: local

server:
  port: 8977

---
spring:
  profiles: aws

server:
  port: 8977


