spring:
  application:
      name: translator

logging:
  level:
    root: info

application:
  properties:
    logging:
      logRequest: true
      logResponse: true
      logRequestForUrls: /*

---
spring:
  profiles: local

server:
  port: 8977


